# Generated by Django 3.0.3 on 2020-06-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCNN', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ImageField(null=True, upload_to='AppCNN/media/'),
        ),
    ]
